export const BirdMap = {
  'category-name': 'birds',
  'base-path': './assets/images/birds/',
  scale: { height: 512, width: 512 },
  assets: {
    'bird-001': { assetName: '001-avocet.svg', description: 'avocet' },
    'bird-002': { assetName: '002-bird.svg', description: 'bird' },
    'bird-003': { assetName: '003-parrot.svg', description: 'parrot' },
    'bird-004': {
      assetName: '004-cardinal.svg',
      description: 'cardinal',
    },
    'bird-005': { assetName: '005-bird.svg', description: 'bird' },
    'bird-006': {
      assetName: '006-chickadee.svg',
      description: 'chickadee',
    },
    'bird-007': { assetName: '007-crane.svg', description: 'crane' },
    'bird-008': {
      assetName: '008-crossbill.svg',
      description: 'crossbill',
    },
    'bird-009': { assetName: '009-duck.svg', description: 'duck' },
    'bird-010': { assetName: '010-eagle.svg', description: 'eagle' },
    'bird-011': { assetName: '011-falcon.svg', description: 'falcon' },
    'bird-012': {
      assetName: '012-flamingo.svg',
      description: 'flamingo',
    },
    'bird-013': { assetName: '013-goose.svg', description: 'goose' },
    'bird-014': { assetName: '014-heron.svg', description: 'heron' },
    'bird-015': { assetName: '015-hen.svg', description: 'hen' },
    'bird-016': { assetName: '016-bird.svg', description: 'bird' },
    'bird-017': { assetName: '017-hoopoe.svg', description: 'hoopoe' },
    'bird-018': {
      assetName: '018-hornbill.svg',
      description: 'hornbill',
    },
    'bird-019': {
      assetName: '019-humming bird.svg',
      description: 'humming bird',
    },
    'bird-020': {
      assetName: '020-flamingo.svg',
      description: 'flamingo',
    },
    'bird-021': { assetName: '021-bird.svg', description: 'bird' },
    'bird-022': {
      assetName: '022-kingfisher.svg',
      description: 'kingfisher',
    },
    'bird-023': { assetName: '023-kiwi.svg', description: 'kiwi' },
    'bird-024': {
      assetName: '024-mandarin.svg',
      description: 'mandarin',
    },
    'bird-025': { assetName: '025-ostrich.svg', description: 'ostrich' },
    'bird-026': { assetName: '026-owl.svg', description: 'owl' },
    'bird-027': {
      assetName: '027-oystercatcher.svg',
      description: 'oystercatcher',
    },
    'bird-028': { assetName: '028-bird.svg', description: 'bird' },
    'bird-029': { assetName: '029-parrot.svg', description: 'parrot' },
    'bird-030': { assetName: '030-parrot.svg', description: 'parrot' },
    'bird-031': { assetName: '031-peacock.svg', description: 'peacock' },
    'bird-032': { assetName: '032-pelican.svg', description: 'pelican' },
    'bird-033': { assetName: '033-penguin.svg', description: 'penguin' },
    'bird-034': { assetName: '034-bird.svg', description: 'bird' },
    'bird-035': { assetName: '035-pigeon.svg', description: 'pigeon' },
    'bird-036': { assetName: '036-quail.svg', description: 'quail' },
    'bird-037': { assetName: '037-raven.svg', description: 'raven' },
    'bird-038': {
      assetName: '038-roadrunner.svg',
      description: 'roadrunner',
    },
    'bird-039': { assetName: '039-robin.svg', description: 'robin' },
    'bird-040': { assetName: '040-seagull.svg', description: 'seagull' },
    'bird-041': { assetName: '041-bird.svg', description: 'bird' },
    'bird-042': { assetName: '042-sparrow.svg', description: 'sparrow' },
    'bird-043': {
      assetName: '043-spoonbill.svg',
      description: 'spoonbill',
    },
    'bird-044': { assetName: '044-swallow.svg', description: 'swallow' },
    'bird-045': { assetName: '045-swan.svg', description: 'swan' },
    'bird-046': { assetName: '046-toucan.svg', description: 'toucan' },
    'bird-047': { assetName: '047-turkey.svg', description: 'turkey' },
    'bird-048': { assetName: '048-vulture.svg', description: 'vulture' },
    'bird-049': { assetName: '049-bird.svg', description: 'bird' },
  },
};
